  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    # --- ADD THIS PERMISSIONS BLOCK ---
    permissions:
      pages: write      # Required to deploy to Pages
      id-token: write   # Required for OIDC token authentication
    # --- END OF ADDED PERMISSIONS BLOCK ---
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # <-- CHANGE TO v4
        # 'with: artifact_name: github-pages' is typically not needed with v4 when using upload-pages-artifact
        # You can optionally remove the 'with:' line below for v4:
        # with:
        #   artifact_name: github-pages 
